DROP table IF EXISTS kafka_app.contacts;
CREATE SCHEMA IF NOT EXISTS kafka_app;

CREATE TABLE kafka_app.contacts (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    userid int8 NULL,
    email text NULL,
    name text NULL,
    age int4 NULL,
    CONSTRAINT contact_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_contacts_email ON kafka_app.contacts USING btree (email);

INSERT INTO kafka_app.contacts (id, userid, email, name, age)
VALUES
    ('1',
     'u-4234',
     'cderetziy@gmail.com',
     'Christos Deretzis'
     25)
ON CONFLICT (id) DO NOTHING;